### ISSUE TITLE
How to make a dataset for your own project?

### ISSUE THREAD

**Issue by U-zzd** [PSilling/demis#1]
Make a dataset for your own project

**Comment by PSilling** [comment]
Hi! This project is still heavy under development, but the core is going to utilise [LoFTR](https://github.com/zju3dv/LoFTR). For now, you can reference their code and issues, they discuss what you need for your own dataset (images, depth maps, camera intrinsics and extrinsics). Regarding DEMIS in particular, code and documentation should be finished in about 3 months. Closing this for now and thank you for your interest and patience!
